service: ec2-sg-api

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeRegions"
        - "ec2:DescribeSecurityGroups"
      Resource: "*"

functions:
  authorizer:
    cors: true
    handler: src/handlers.authorizer
  list:
    handler: src/handlers.list
    events:
      - http:
          authorizer: authorizer
          path: /
          method: GET

plugins:
  - serverless-offline