service: list-ec2-security-groups

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeRegions"
        - "ec2:DescribeSecurityGroups"
      Resource: "*"

functions:
  list:
    handler: src/handlers.list
    events:
      - http:
          path: /
          method: GET

plugins:
  - serverless-offline